spring:
  application:
    name: nguyenvanminh-22003405-spring-mongodb
  data:
    mongodb:
      uri: mongodb+srv://nvminh1602:zMI8V5g92XoBNmsn@cluster0.sh1iqcw.mongodb.net/www_regular_spring_mongodb?retryWrites=true&w=majority&appName=Cluster0
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    resources:
      static-locations: /resources/

